---
title: "XH-pi frequency vs resolution"
author: "Emma Rand"
date: "22/08/2019"
output:
  pdf_document: bookdown::pdf_document2
  html_document: bookdown::html_document2
  word_document: default
bibliography: ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r pkgs}
library(tidyverse)
library(data.table)
library(viridis)
library(MASS)
library(janitor)
```

```{r}
# Get density of points in 2 dimensions.
# @param x A numeric vector.
# @param y A numeric vector.
# @param n Create a square n by n grid to compute density.
# @return The density within each square.
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

```


```{r}
file <- "../xhpi_data_v3/xhpi_freq_res.csv"
resfreq <- read.csv(file) %>% clean_names()

glimpse(resfreq)
```



```{r}
mod <- lm(data = resfreq, freq_per_100 ~ resolution)
intercept <- summary(mod)[["coefficients"]][1,1]
intercept_se <- summary(mod)[["coefficients"]][1,2]
slope <- summary(mod)[["coefficients"]][2,1]
slope_se <- summary(mod)[["coefficients"]][2,2]
```


```{r}
resfreq$density <- get_density(resfreq$resolution, 
                               resfreq$freq_per_100, n = 100)
ggplot(data = resfreq, aes(x = resolution, y = freq_per_100, colour = density)) +
  geom_point() +
  geom_smooth(method="lm")+
  scale_color_viridis() +
  geom_hline(yintercept = intercept) +
  geom_hline(yintercept = intercept + intercept_se) +
  geom_hline(yintercept = intercept - intercept_se)
```

```{r}
library(rollRegres)



# test
# simulate data
width  <- 20
# n <- 20
# df <- data.frame(y = sort(rnorm(n)), x = sort(rnorm(n)))
#plot(df)
# fits <- roll_regres(y ~ x, df, width = width, do_compute = "sigmas")
# tail(fits$coefs)
# tail(fits$sigmas)

window <-  19
mod1 <- lm(data = df[1:window,], y ~x)
mod2 <- lm(data = df[(1+1):(window+1),], y ~x)
pred1 <- predict(mod1, interval = "predict")
pred2 <- predict(mod2, interval = "predict")
df1 <- data.frame(df[1:window,], pred1,win=1)
df2 <- data.frame(df[(1+1):(window+1),], pred2,win=2)
df3 <- rbind(df1,df2)
df3 <- df3 %>% gather(-x, -y, -fit, -win, key = line, value = value)


ggplot() +
  geom_line(data = df3, aes(x = x, y = value, linetype=factor(win), shape = line)) +
  geom_point(data = df, aes(x = x, y = y)) +
  geom_smooth(data = df, aes(x = x, y = y),
              method = "lm", color = "black")


for(i in 1:(nrow(df)-window+1)) {
  rowstart <- i
  rowstop <- i + window - 1
  print(c(i, rowstart, rowstop))
}




```


